export const backgroundConverter = {
  "01d": require("../../assets/weatherImages/clearsky.jpg"),
  "02d": require("../../assets/weatherImages/fewclouds.jpeg"),
  "03d": require("../../assets/weatherImages/scarattedClouds.jpg"),
  "04d": require("../../assets/weatherImages/brokenClouds.jpg"),
  "09d": require("../../assets/weatherImages/chuviscando.jpg"),
  "10d": require("../../assets/weatherImages/rain.jpg"),
  "11d": require("../../assets/weatherImages/storm.jpg"),
  "13d": require("../../assets/weatherImages/snow.jpg"),
  "50d": require("../../assets/weatherImages/mist.jpg"),
  "01n": require("../../assets/weatherImages/clearsky.jpg"),
  "02n": require("../../assets/weatherImages/fewclouds.jpeg"),
  "03n": require("../../assets/weatherImages/scarattedClouds.jpg"),
  "04n": require("../../assets/weatherImages/brokenClouds.jpg"),
  "09n": require("../../assets/weatherImages/chuviscando.jpg"),
  "10n": require("../../assets/weatherImages/rain.jpg"),
  "11n": require("../../assets/weatherImages/storm.jpg"),
  "13n": require("../../assets/weatherImages/snow.jpg"),
  "50n": require("../../assets/weatherImages/mist.jpg"),
}